// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cgm_c
VectorXd cgm_c(SEXP As, SEXP bs);
RcppExport SEXP hts_cgm_c(SEXP AsSEXP, SEXP bsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type As(AsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type bs(bsSEXP );
        VectorXd __result = cgm_c(As, bs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
